language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_install:
  - npm install codecov
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
  - master